### ISSUE TITLE
covert catdoc failed

### ISSUE THREAD

**Issue by mendickxiao** [OWASP/Serverless-Goat#10] opened 2019-09-24 05:54 UTC
I found a very strange issue, first, I rebuild the serverless and deploy the API, then run the convert, it is successful, but after the lunch, I tried it again, it is failed. The log is like these:

Error: Command failed: curl --silent -L https://www.puresec.io/hubfs/document.doc | ./bin/catdoc -
/bin/sh: ./bin/catdoc: Permission denied

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at exports.handler (/var/task/index.js:31:29)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

I googled in the website and found these page:
https://sourceforge.net/p/htdig/mailman/message/10969346/
It sounds as though you have not installed catdoc, only compiled it.

Catdoc must be installed, as described in the INSTALL file, so that it ca=
n
find the cp1251.txt file and any others it may need.

Do we really need to install the catdoc?

I clone the code in my local, and test it.
[root@lin-0aff6d1a convert]# curl --silent -L https://www.puresec.io/hubfs/document.doc | ./bin/catdoc -
Cannot load charset cp1251 - file not found

The same error, and I installed the catdoc, it is work:
[root@lin-0aff6d1a ~]# curl --silent -L https://www.puresec.io/hubfs/document.doc | catdoc -
A Poison Tree / William Blake:<br/><br/>

I was angry with my friend:<br/>

I told my wrath, my wrath did end. <br/>

I was angry with my foe: <br/>

I told it not, my wrath did grow. <br/><br/>

And I watered it in fears, <br/>

Night and morning with my tears; <br/> 

And I sunned it with smiles, <br/>

And with soft deceitful wiles. <br/>

And it grew both day and night, <br/>

Till it bore an apple bright. <br/>

And my foe beheld it shine. <br/>

And he knew that it was mine, <br/><br/>

And into my garden stole<br/>

When the night had veiled the pole; <br/> 

In the morning glad I see<br/>

My foe outstretched beneath the tree. <br/>

**Comment by 0xh0b0** [comment] 2019-09-24 07:24
duplicate of #4 
Please try to use the latest version of the code, the issue was fixed 7 months ago in #5

**Closed as completed by 0xh0b0** 2019-09-24 07:24 UTC
